### ISSUE TITLE
Allow testing client with different codecs

### ISSUE THREAD

**Issue by scoquelin** [scoquelin/arugula#15]
So far we only supported `RedisCodec[String, String]` as the default codec format for Redis key and values.

Let's try to plumb support for testing with multiple codecs, starting with `RedisCodec[String, Long]`

**Comment by 72squared** [comment]
I think [String , ByteArray] might be more common. That is where I have used different codecs. You can always cast a string to longOption

**Comment by 72squared** [comment]
I remember where the binary codec is needed ... when you dump and restore keys, the values are binary values not strings.
